### ISSUE TITLE
corrupted image in the dataset

### ISSUE THREAD

**Issue by segalinc** [rkosti/emotic#10]
Just wanted to report that emotic/framesdb/images/frame_0cs63q843g5bdvq5.jpg is corrupted
some lines of pixels at the bottom of the image are broken.

**Comment by rkosti** [comment]
Thanks! I just updated the repos with the cut-out image. I would suggest to either get rid of it or use this new file.

**Comment by segalinc** [comment]
Thank you!!

Cristina

**Comment by segalinc** [comment]
> Thanks! I just updated the repos with the cut-out image. I would suggest to either get rid of it or use this new file.

which link has the new file?

**Comment by rkosti** [comment]
![frame_0cs63q843g5bdvq5](https://user-images.githubusercontent.com/20704168/101239744-5d454500-36ea-11eb-8239-b42b4fba4ee7.jpg)
Pami_19_Dataset link has the new file.
I also attach the edited file here, in case you do not want to download the
whole dataset again.

-
Ronak

**Comment by segalinc** [comment]
Awesome thanks!

Cristina

**Comment by missyun125** [comment]
@segalinc I can't download EMOTIC dataset on the official website. Can you send the dataset to my email（604133530@qq.com）?
