### ISSUE TITLE
Help finding the dataset!

### ISSUE THREAD

**Issue by missyun125** [rkosti/emotic#11]
I can't download EMOTIC dataset on the official website.

**Comment by Tandon-A** [comment]
@missyun125

It seems that the access to the dataset is changed. You now need to fill the [access form](https://docs.google.com/forms/d/e/1FAIpQLScXwxhEZu7RpHwgiRqVfb09GzHSSyIm64hJQMgHSLm75ltsFQ/viewform) first. After reviewing the details, [Ronak](https://github.com/rkosti) would you send the link to the dataset.

Regards,
Abhishek

**Comment by missyun125** [comment]
> @missyun125
> 
> It seems that the access to the dataset is changed. You now need to fill the [access form](https://docs.google.com/forms/d/e/1FAIpQLScXwxhEZu7RpHwgiRqVfb09GzHSSyIm64hJQMgHSLm75ltsFQ/viewform) first. After reviewing the details, [Ronak](https://github.com/rkosti) would you send the link to the dataset.
> 
> Regards,
> Abhishek

Thank u !!!
