### ISSUE TITLE
One image in test data

### ISSUE THREAD

**Issue by mishimario** [rkosti/emotic#13]
I downloaded EMOTIC dataset, and checked annotation file. But I found the image of '12ctuwhai2qxczp2wf.jpg' doesn't have the complete annotation. Class label annotation is missing on the image. Do you know this image's label or something? Thank you in advance!

**Comment by rkosti** [comment]
Strange. Can you check again? 
The aggregated categorical labels are: `Affection, Confidence, Excitement, Happiness, Peace, Sympathy` & `Valence/Arousal/Dominance` averages are: `8/6/7`
