### ISSUE TITLE
How to do a single image inference ? 

### ISSUE THREAD

**Issue by GKalliatakis** [rkosti/emotic#2]
After gracefully providing your trained CNN, I would like to know how can I do a single image inference using that model (torch7 format).

**Comment by rkosti** [comment]
You can download the code for single image inference [here ](https://www.dropbox.com/s/jeipdv8nrva46qo/test_single_image_cvpr17model.lua?dl=0)

**Comment by GKalliatakis** [comment]
I tried the code you provided but I am receiving the following error 

```
Environment:
	Torch 7.0

Code:
	model:evaluate();

Error:

attempt to call method 'evaluate' (a nil value)
stack traceback:
	[C]: in function 'evaluate'
	/grig_tes.lua:26: in function 'testImage'
	/grig_tes.lua:57: in main chunk
```

any thoughts on this ?

**Comment by rkosti** [comment]
Yes, the code will not run **out-of-box**. It is just a general format, you need to make sure all the variables are provided accordingly.

**Comment by Tandon-A** [comment]
@rkosti 

Hello Ronak, 

In the script, mentioned in your answer above, you are passing the context image and the body image through the model and then calculating the errors. 

The categorical prediction would be an array of length(categories) in this case 26. How do you then perform inference over an image, i.e. tell the categorical predictions for an image? 
Do you compare the values of categorical prediction array with a threshold to convert them to a binary value? If yes, what threshold value is used? 

Please help. 

Regards 
Abhishek

**Comment by rkosti** [comment]
Dear Abhishek (@Tandon-A), 
For inference over a single image, we use the thresholds for each emotion category and the output values for continuous dimensions. 
For emotion categories, we find the thresholds where Precision=Recall over the whole test set of images. Then we use these thresholds (category-wise) to make the inference for single (random) images. 
Thanks for bringing this to notice, I will update the code by including the single image inference , and will also share the thresholds we used for our PAMI paper.

**Comment by rkosti** [comment]
I have now added the code to do single image inference on our PAMI model. The file is added in the main repo: https://github.com/rkosti/emotic/blob/master/single_image_inference.lua

**Comment by Tandon-A** [comment]
Thank you sharing the script and the thresholds.
