### ISSUE TITLE
How to deal with the val/test images with several annotations?

### ISSUE THREAD

**Issue by Sampson-Lee** [rkosti/emotic#5]
Hi, thanks for your good work in emotion recognition. Could you help me in following question?

I notice that there are different annotations for one image in val/test data. How to deal with the val/test images with several annotations? Could it be reasonable to calculate the Average Precision of all annotations?

Thanks again. Look forward to your reply.

**Comment by rkosti** [comment]
Yes, that is true. Each of the validation/test images have multiple annotations. We take the union of the discrete annotations (26 emotion categories like happiness, sadness, etc) and average of the continuous dimensions (valence, arousal and dominance individually) for all the available annotations of test/val set to calculate the Average Precision.

**Comment by Sampson-Lee** [comment]
@rkosti Thanks a lot.
