### ISSUE TITLE
What is the mAP when you use normal backbone like resnet34 and normal data sampling?

### ISSUE THREAD

**Issue by Sampson-Lee** [rkosti/emotic#6]
Hi, sorry for bothering you again. Could you help me in following question?

I used a resnet34 as backbone and normal data sampling, but got 10% mAP at test images. I wonder whether the types of backbone and data sampling make a big difference for the result. 

Thanks again. Look forward to your reply.

**Comment by Sampson-Lee** [comment]
Maybe I generates the wrong test/val labels.

**Comment by rkosti** [comment]
probably yes. It happened to me as well. In my case, using deeper networks as backbone dropped the model performance by ~8 mAP. It can be attributed to the fact that the problem is too complex (in the given model design) to be tackled by deeper architectures.
