### ISSUE TITLE
Performance increase in using uniform sampling

### ISSUE THREAD

**Issue by Tandon-A** [rkosti/emotic#7]
Hello Ronak, 

Thank you for providing code and scripts to run the code. 

I have a small doubt regarding the training setup. 

In the CVPR paper, you have said that with uniform sampling, i.e. having at least one instance of each discrete category in each batch, you observe better results.  Can you tell the performance increase in using uniform sampling over regular random shuffling? 

Also, uniform sampling is not mentioned in the PAMI paper. Do you not use it in the latest experiments? 

Regards 
Abhishek

**Comment by rkosti** [comment]
Hi Abhishek, 
The performance increase was empirically observed to be between 2-4 pp (percentage points). In the PAMI also we follow the same sampling method.

**Comment by rkosti** [comment]
Hi Abhishek, 
Thanks for pointing out regarding the use of uniform sampling method. We did not use it for PAMI, we used random sampling. However, we also weighted the classes while training based on their occurrences across EMOTIC dataset.
